export enum MessageType {
  VIDEO_ERROR = 'VIDEO_ERROR',
  AUDIO_ERROR = 'AUDIO_ERROR',
  API_URL_SAVED = 'API_URL_SAVED',
  API_URL_SAVE_FAILED = 'API_URL_SAVE_FAILED',
  CACHE_CLEARED = 'CACHE_CLEARED',
}
